apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    app: kubia
    #env: prod
spec:
  #nodeSelector:
  #  gpu: kubia-gpu
  containers:
    - image: luksa/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
        #- name: http
        #  containerPort: 80
        #- name: https
        #  contaierPort: 8443